<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RpgForge.Core\RpgForge.Core.csproj" />
    <ProjectReference Include="..\RpgForge.Claude\RpgForge.Claude.csproj" />
    <ProjectReference Include="..\RpgForge.Tools\RpgForge.Tools.csproj" />
    <ProjectReference Include="..\RpgForge.Agents\RpgForge.Agents.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
