<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RpgForge.Core\RpgForge.Core.csproj" />
    <ProjectReference Include="..\RpgForge.Claude\RpgForge.Claude.csproj" />
    <ProjectReference Include="..\RpgForge.Tools\RpgForge.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.39.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
